server:
  port: 8903

spring:
  application:
    name: client-feign-zhl
  redis:
    host: 127.0.0.1
    port: 6379

eureka:
  client:
    #eureka服务地址
    service-url:
      defaultZone: http://localhost:8848/eureka
feign:
  hystrix:
    #开启断路器
    enabled: true