server:
  port: 8854

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shun?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  data:
    mongodb:
      host: 192.168.1.23
      port: 27017
      database: 1903a

  application:
    name: provider-fjs

mybatis:
  mapper-locations: classpath:mybatis/*.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8848/eureka
