server:
  port: 8850

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/car?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  application:
    #应用名称
    name: provider-zyf

mybatis:
  #mybatisxml文件的地址
  mapper-locations: classpath:mybatis/*.xml
  #showsql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    #eureka服务地址
    service-url:
      defaultZone: http://localhost:8848/eureka
